env: mpe

env_args:
  map_name: "simple_spread"
  obs_instead_of_state: True
  obs_last_action: False
  episode_limit: 25

test_greedy: True
test_nepisode: 20
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2010000
